# Streamlit Cloud secrets
# Preencher em https://share.streamlit.io/ -> app settings -> Secrets
# As credenciais da planilha Google Sheets e Runrun.it

[rds]
database_url = "sqlite:///chat_ufac.db"

[runrunit]
app_key = "9c13b7d24e4f38782e929984559f8aef"
user_token = ""
